JuliaSparse/SparseArrays.jl

- docs/make.jl
Fixes #2 
This pull request:
1. Builds the docs with `strict = [:doctest]`. This ensures that if there is a doctest failure, then the docs build fails, and gives a red ❌ on CI.
2. Fixes the broken doctests by ensuring that `using SparseArrays; using LinearAlgebra` is always run at the beginning of every `jldoctest` block.
> [CI] Build the docs with `strict = [:doctest]`, and fix the broken doctests

- docs/src/index.md
- src/SparseArrays.jl
- src/sparsematrix.jl
- src/sparsevector.jl
- test/sparse.jl
- test/sparsevector.jl
Ideally, this would be merged with rebase and merge but that is disabled so I guess we just go with a merge commit.
> Add the missing commits from Julia repo here

- .codecov.yml
Same motivation as https://github.com/JuliaLang/Pkg.jl/pull/2910
> Only show the Codecov commit statuses on pull requests; do not show the Codecov commit statuses on commits on `main`

- README.md
Also, I went to the Codecov settings for this repo (https://app.codecov.io/gh/JuliaLang/sparsearrays.jl/settings), and in the "Default Branch}" section, I changed it from `master` to `main`.
> README: fix the Codecov badge to point to the `main` branch (not the `master` branch)

- test/basetests.jl
Move various sparse tests from julia base tests into basetests.jl here.
This leaves mentions of SparseArrays in hashing.jl, ambiguous.jl (sparse tests are excluded there), and precompile.jl. I believe these need to stay in base.
```
➜  test git:(vs/sparsetests) ✗ git grep SparseArrays | cat
ambiguous.jl:using LinearAlgebra, SparseArrays, SuiteSparse
ambiguous.jl:    STDLIBS = filter!(x -> x != "LinearAlgebra" && x != "SparseArrays" && # Some packages run this test themselves
hashing.jl:using Random, LinearAlgebra, SparseArrays
precompile.jl:                 :SparseArrays, :Statistics, :SuiteSparse, :TOML, :Tar, :Test, :UUIDs, :Unicode,
```
> Add the tests from base

- src/sparsematrix.jl
- test/higherorderfns.jl
https://github.com/JuliaLang/julia/pull/43604 has been merged.
Thus we don't need these code.
> Code clean for `extrema`

- .github/workflows/backport.yml
This pull request adds the `tibdex/Backport` GitHub Action.
The documentation for this Action is available here: https://github.com/tibdex/backport
> Add the `Backport` GitHub Action workflow, which automatically backports PRs when you add the backport label

- test/basetests.jl
- test/testgroups
Here's a tiny fix for some broken syntax I noticed in test/basetests.jl
By the way, do people realize that the tests in `test/basetests.jl` are not currently being included?
> Fix syntax in basetests.jl

- src/sparsematrix.jl
This PR only changes 2 lines - the signatures of `_checkbuffers` and `_goodbuffers` as mentioned in the linked issue.
These methods check the assumptions on colptr, rowval and nonzeros and thus should work for all AbstractSparseMatrixCSC. Changing the signature also removes the need for every subtype to implement it, which will fix the packages broken by [JuliaLang/julia/pull/40523](https://github.com/JuliaLang/julia/pull/40523) such as [ThreadedSparseArrays.jl/issues/9](https://github.com/jagot/ThreadedSparseArrays.jl/issues/9)
Fixes #9
> Change type signature of _checkbuffers and _goodbuffers

- docs/src/index.md
- src/sparsematrix.jl
- test/sparse.jl
As discussed in #18, this adds a border to sparse matrices which are printed using Braille.
Closes #18.
> Add borders when showing sparse matrices with Braille

- test/sparse.jl
It doesn't make sense to test that `sprand(BigFloat, ...)` throws a `MethodError`, as this function will work as soon as https://github.com/JuliaLang/julia/issues/17629 is fixed.
In particular, this test is blocking https://github.com/JuliaLang/julia/pull/44714
> remove invalid test for failing sprand(BigFloat)

- Project.toml
- src/sparsevector.jl
- test/sparsevector.jl
fixes https://github.com/JuliaLang/julia/issues/44978
> fix findmin/findmax

- src/sparsevector.jl
- test/sparsevector.jl
After JuliaLang/julia#45028, it will be more recommended to use this
more type stable version of `cat_t`.
> use more type stable `cat_t` implementation

- src/abstractsparse.jl
- src/sparsevector.jl
- test/sparsevector.jl
Before:
```
julia> SparseVector(div(typemax(Int32), 2), Int[1], Int[1])
1073741823-element SparseVector{Int64, Int64} with 1 stored entry:
[1         ]  =  1
```
After:
```
julia> SparseVector(div(typemax(Int32), 2), Int[1], Int[1])
1073741823-element SparseVector{Int64, Int64} with 1 stored entry:
[1]  =  1
```
The difference here is that we look at the maximum *stored* coordinate
rather than the maximum *possible* coordinate. This will retain the
alignment benefits of printing with padding while avoiding unnecessary
padding when only the first few elements of a large sparse vector are
set.
> Remove unnecessary padding in coord-form printing of large sparse vectors

- docs/src/index.md
> Doc alternative space array package

- test/umfpack.jl
Fixed for [1.8](https://github.com/JuliaLang/julia/issues/45736#issuecomment-1166253921) and [master](https://github.com/JuliaLang/julia/pull/45644).
> Re-enable the float16 tests

- .codecov.yml
the code coverage has dropped drastically since suitesparse was merged. i don't think it's meaningful to calculate the code coverage on these files.
> remove solvers/lib form codecov

- Project.toml
- test/cholmod.jl
> remove depedency on DelimitedFiles

- src/sparsevector.jl
- test/sparsevector.jl
Fixes https://github.com/JuliaLang/julia/issues/45937.
Should be backported to v1.8.
> Let `length(::SparseVector{Tv,Ti})` return `Ti`

- src/sparsevector.jl
- test/sparsevector.jl
> Generalize `findnz` and reduction to `AbstractSparseVector`s

- docs/src/index.md
- src/solvers/umfpack.jl
- test/umfpack.jl
i had two questions, 
frist do we have style? if so
```julia
function umfpack_numeric!(U::UmfpackLU{ComplexF64,$itype}; reuse_numeric = true, q = nothing)
```
or
```julia
function umfpack_numeric!(U::UmfpackLU{ComplexF64,$itype}; reuse_numeric=true, q=nothing)
```
another question is how i can test this? i don't seem to be able to call AMD.jl when i run julia with `--project`.
i get
```
ERROR: MethodError: no method matching colamd(::SparseMatrixCSC{Float64, Int64}, ::Colamd{Int64})
Closest candidates are:
colamd(::SparseArrays.SparseMatrixCSC{F, Int64}, ::Colamd{Int64}) where F at ~/.julia/packages/AMD/aB8em/src/COLAMD.jl:81
colamd(::Symmetric{F, SparseArrays.SparseMatrixCSC{F, Int64}}, ::Colamd{Int64}) where F at ~/.julia/packages/AMD/aB8em/src/COLAMD.jl:106
colamd(::Hermitian{F, …
```
> Add support for qsymbolic to umfpack

- src/SparseArrays.jl
- src/higherorderfns.jl
- src/sparsematrix.jl
- src/sparsevector.jl
- test/sparsematrix_ops.jl
- test/sparsevector.jl
> Determine correct eltype in sparse map

- src/solvers/spqr.jl
- src/sparsematrix.jl
- test/spqr.jl
> Speed up `SparseMatrixCSC(::AbstractQ)` constructor and multiplication

- src/solvers/cholmod.jl
- src/solvers/spqr.jl
- test/cholmod.jl
- test/runtests.jl
See https://github.com/JuliaSparse/SparseArrays.jl/pull/204
This PR takes the path of least resistance and just uses `task_local_storage`. The part that most needs review is the addition of a call to `cholmod_l_finish`. This is attached to the `cholmod_common` object which is lazily created in each task (which uses CHOLMOD). 
I *think* this is correct, but I'm not 100% certain on the lifetime of `task_local_storage`.
> Remove Thread-local storage from CHOLMOD and SPQR

- src/solvers/cholmod.jl
Per Fredrik this avoids allocating a common object every time it is used.
> Avoid allocating objects with funcitonal form of get!

- docs/src/index.md
Update documentation on double transposes needing copies, and that non-standard CSC matrices will not display correctly. I think this is sufficient to close #82.
> Update double transpose note in docs

- docs/src/index.md
- src/sparsematrix.jl
- test/umfpack.jl
`similar` does slightly different things for sparse matrices. Document that. Fix #14 
I'm not sure if this is the right way to add these docs. Would appreciate a review from someone more knowledgable.
> Add documentation for similar of sparse matrices

- src/solvers/umfpack.jl
- test/umfpack.jl
Per @Keno we want to avoid serializing uninitialized memory, and the workspace is not information required to reconstruct a factorization. We came to the decision that this was within the semantics of `serialize`/`deserialize`, and that aliased workspaces after deserialization was a dangerous property.
On master we serialize pointers, which will only work while that pointer remains alive (and could easily segfault). There is no way to serialize the symbolic and numeric factorizations via arbitrary IO.
There are `umfpack_{load | save}_{numeric | symbolic}` functions in UMFPACK, but they take a file path. It would be ideal to add this capability to save the factorization itself, not just the info to reconstruct it, but I recall dealing with FILE handles for SuiteSparseGraphBLAS.jl was very …
> Don't serialize pointers and workspace, add `lu!(F::UmfpackLU)`

- .github/workflows/ci.yml
Let's try to make sure we can keep this package going on Julia stable, and maybe even Julia 1.6.
@dkarrasch I believe the `Base.extremamap` is Julia 1.8 only (I believe it should have been added through your recent PR).  If possible, it would be nice to make the package in its current shape work on Julia 1.7, but if not, we can make 1.8 the minimum required going forward, but be more conservative going forward about using features in new Julia versions.
My purpose here is to just be a bit more deliberate.
> Enable julia stable in CI

- src/sparsematrix.jl
- test/sparsematrix_ops.jl
Closes https://github.com/JuliaSparse/SparseArrays.jl/issues/226.
> Implement efficient sparse array comparisons

- src/SparseArrays.jl
- src/readonly.jl
we only use it when it returns a vector, so  i think it's good idea for AbstractMatrixCSCs that don't use Vectors (like Fixed)
> decrement should always return a vector

- src/sparsevector.jl
- test/sparsevector.jl
Fixes the `vcat` aspect of #251.
> Fix `vcat` of sparse vectors with numbers

- .github/workflows/ci.yml
> On the backports-v1.8 branch, run CI on v1.8

- src/SparseArrays.jl
- src/sparsematrix.jl
- src/sparsevector.jl
See https://github.com/JuliaLang/julia/pull/46759.
> Fix direction of circshift

- docs/src/index.md
fkeep! doesn't have a docstring, and including it in the documentation errors when building julia.
> Remove fkeep! from the documentation

- src/sparsematrix.jl
- src/sparsevector.jl
- test/sparsematrix_constructors_indexing.jl
- test/sparsematrix_ops.jl
- test/sparsevector.jl
> Make sure reductions benefit from sparsity

- src/sparsematrix.jl
- src/sparsevector.jl
- test/sparsematrix_constructors_indexing.jl
- test/sparsevector.jl
This is useful to have a unified way to create sparse and dense vectors.
Will add tests if the feature is considered useful / needed
> add undef initializers

- src/sparsevector.jl
- test/higherorderfns.jl
- test/issues.jl
- test/sparsematrix_ops.jl
> add == for vectors

- src/readonly.jl
- src/sparsevector.jl
This patch fixes the tests run in Base, i.e.
```
@test isempty(detect_ambiguities(Core, Base; recursive=true))
```
passes. Enabling the tests seemed much more complicated (#267) so let's do this for now to unblock the update in JuliaLang/julia.
> Fix ambiguities with Base.

- .github/workflows/ci.yml
- src/SparseArrays.jl
- src/sparsematrix.jl
- src/sparsevector.jl
- test/sparsevector.jl
Co-authored-by: Steven G. Johnson <stevenj@mit.edu>
Note: I want to be sure the attribution is correct here, I *think* it should say "authored by Jerry and Steven" and "committed by Wimmerer".
Backported PRs:
> Backports for Julia v1.8.x

- src/SparseArrays.jl
- src/abstractsparse.jl
- src/sparsematrix.jl
- src/sparsevector.jl
I'm presuming that the first bounds check is sufficient to cover the later ones being omitted. Then the user can control the first bounds checks for this method at the call site.
In my code which is highly dominated by sparse array lookups, this increased overall speed by 5%.
> Elide bounds checks in `getindex`

- src/sparsematrix.jl
- src/sparsevector.jl
- test/sparsematrix_ops.jl
- test/sparsevector.jl
> Fix `all`/`any` on empty sparse arrays

- src/solvers/umfpack.jl
- test/umfpack.jl
@JeffBezanson is this more acceptable? The semantics of the previous version didn't really match `deepcopy` anyway (only certain fields were copied). 
Can `copy` signature be modified without affecting Base specialization changes?
> Remove deepcopy from UMFPACK, add kwarg to copy

- src/linalg.jl
I'm not sure why this hasn't come up anywhere, but it may be that it simply lead to performance penalties. In any case, for a while adjoints of triangular matrices are passed to the wrapped matrix while the triangular wrapper is flipped. This should be backported to v1.8.
> Fix order of triangular and adjortrans wrappers

- src/SparseArrays.jl
- src/sparsematrix.jl
- src/sparsevector.jl
Will the Base PR be backported to v1.8.2, or not? I.e., can this be included in our backport PR, which hopefully still makes it for v1.8.2?
> Remove temporary circshift direction workaround

- src/sparsevector.jl
- test/sparsematrix_constructors_indexing.jl
- test/sparsevector.jl
Co-authored-by: David Hien <david.hien@web.de>
Fixes ```spzeros(k,0)[:]``` and ```spzeros(0,k)[:]``` throwing errors or segmentation faults.
> Bugfix in getindex for Matrices with one dimension 0

- src/SparseArrays.jl
`Base.Order` defines `Forward` and `Base.Sort` uses it.
> Use `Forward` from the module it is defined from

- src/sparsematrix.jl
- test/sparsematrix_constructors_indexing.jl
This PR makes it more memory efficient to create the sparsity pattern,  i.e. when you dont care about the values of `V`.
For a cube mesh with 70x70x70 elements (and linear interpolation with 1 dof per node), i get these benchmarks:
```
@show 2*Base.summarysize(I)/(1024^2)        #Memory of I and J
@btime sparse($I, $J, 1.0)                  # This PR
@btime sparse($I, $J, fill(1.0, length(J))) # Previously
```
```
(2 * Base.summarysize(I)) / 1024 ^ 2 = 340.42230224609375 #MB
200.528 ms (17 allocations: 321.74 MiB)
318.534 ms (21 allocations: 662.17 MiB)
357911×357911 SparseMatrixCSC{Float64, Int64} with 9393931 stored entries:
⎡⠻⣦⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⎤
⎢⠀⠈⠻⣦⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⎥
⎢⠀⠀⠀⠈⠻⣦⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⎥
⎢⠀⠀⠀⠀⠀⠈⠻⣦⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⎥
⎢⠀⠀⠀⠀⠀⠀⠀⠈⠻⣦⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⎥
⎢⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠻⣦⡀⠀⠀⠀⠀⠀⠀⠀⎥
⎢⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠻⣦⡀⠀⠀⠀⠀⠀⎥ …
```
> Improved memory usage when creating the sparsity pattern

- src/sparsematrix.jl
I noticed that the `rfn` argument of `sprand` was poorly documented:
1. We didn't say what its arguments should be.
2. We didn't say clearly that it defaults to `rand`
3. The type `T` argument goes in a different place if `rfn` is passed.   Moreover, although in this case you can pass `T` as the *last* argument, it seems that it doesn't really work — if it doesn't match the return type of `rfn`, it is ignored!  So, it seems better to leave that undocumented for now until we decide what to do with it.
> document rfn argument of sprand

- src/sparsematrix.jl
- test/sparsematrix_constructors_indexing.jl
With this patch the output buffers to `sparse!` are resized in order to satisfy the buffer length checks in the `SparseMatrixCSC` constructor that were introduced in JuliaLang/julia#40523. Previously `csccolptr` was never resized, and  `cscrowval` and `cscnzval` were only resized if the buffers were too short (i.e. never truncated).
The requirement `length(csccolptr) >= n + 1` could be kept, but seems unnecessary since all buffers need to be resized anyway (to pass the constructor checks).
In particular this fixes calling `sparse!` with `I`, `J`, `V` as both input and output buffers: `sparse!(I, J, V, m, n, ..., I, J, V)`.
Fixes #313.
> Resize buffers in `sparse!` to satisfy buffer checks in constructor

- src/solvers/spqr.jl
- test/spqr.jl
I don't know why this didn't come up earlier, but the size of the Q factor was missing. This now popped up in https://github.com/JuliaLang/julia/pull/46196. It can be removed once that one is merged, and then fall back to the generic `show` method defined there.
> Fix `show` of `QRSparseQ`

- src/sparsematrix.jl
- src/sparsevector.jl
- test/spqr.jl
It turns out that in a few packages (in particular optimization-related ones) there is multiplication of `AbstractQ` instances and `SparseArray`s. Due to a lack of specialization, this falls back to `_generic_matmatmul!`, which is horrible for at least three reasons: (1) it's computing the elements of the matrix representation of `Q` one-by-one; (2) it doesn't use sparsity at all; and (3) it writes the dense result into an empty sparse output array. I have a hard time imagining anything worse than that. This popped up once we drop `AbstractQ <: AbstractMatrix` subtyping, see https://github.com/JuliaLang/julia/pull/46196.
> Specialize multiplication of AbstractQ with sparse arrays

- src/SparseArrays.jl
- src/solvers/spqr.jl
- src/sparsematrix.jl
- src/sparsevector.jl
The recent change in #317 is giving heavy ambiguity pain when tested on https://github.com/JuliaLang/julia/pull/46196, so I think it is much better to restrict to the `AbstractQ` subtypes owned by `LinearAlgebra`. Other packages providing `AbstractQ`s will need to define what to do when multiplying their Q with a sparse array.
> Restrict AbstractQ multiplication to LinearAlgebra types

- src/sparsevector.jl
For vector `sv=sprand(n,0.2)`:
```julia
Vector: n = 16
master:   119.365 ns (1 allocation: 192 bytes)
pr:       45.455 ns (1 allocation: 192 bytes)
Vector: n = 65536
master:   2.682 ms (2 allocations: 512.05 KiB)
pr:       37.200 μs (2 allocations: 512.05 KiB)
```
<details>
<summary>Benchmark code with more cases</summary>
```julia
julia> using SparseArrays, BenchmarkTools
julia> function collect_pr(x::Union{AbstractSparseVector,AbstractSparseMatrix})
if Base.has_offset_axes(x)
return Base._collect_indices(axes(x), x)
else
return Array(x)
end
end;
julia> for n in [16^i for i in 1:4]
sv = sprand(n, 0.2)
println("Vector: n = $n")
print("master: "); @btime collect($sv)
print("pr:     "); @btime collect_pr($sv)
if n <= 16^3
println("Matrix: n = $n")
sm = sprand(n, n, 0.2)
print("master: "); …
```
> Faster collect

- src/linalg.jl
- src/solvers/cholmod.jl
- test/cholmod.jl
Fixes https://github.com/JuliaLang/julia/issues/48095.
> Make `cholmod` vector solve return vector

- src/linalg.jl
- test/linalg.jl
There were `@inbounds` annotations without any size checks, which lead to segfaults.
> Add bounds checks to inplace `kron!`

- src/solvers/cholmod.jl
- test/cholmod.jl
This extends the same behavior of `Factor` to adjoints of `Factor`s, and helps to prevent a potential method ambiguity in https://github.com/JuliaLang/julia/pull/46874.
> Allow real adjoint cholmod solve with complex rhs

- src/solvers/cholmod.jl
This reverts #327 partially. I misread the comment, and we don't have ambiguity testing with LinearAlgebra, apparently.
> Add back explicit typevars in cholmod

- src/sparsematrix.jl
- test/sparsematrix_constructors_indexing.jl
- test/sparsevector.jl
Ref #312 @ViralBShah 
(I also added a test to cover the `collect` - calls)
```julia
using SparseArrays, BenchmarkTools
for n in [16^i for i in 1:3]
print("n = $n: ")
sm = sprand(n, n, 0.2)
@btime collect($sm)
end
n = 16:   367.136 ns (1 allocation: 2.12 KiB)
n = 256:   64.300 μs (2 allocations: 512.05 KiB)
n = 4096:   45.581 ms (2 allocations: 128.00 MiB)
n = 16:   261.872 ns (1 allocation: 2.12 KiB)
n = 256:   23.200 μs (2 allocations: 512.05 KiB)
n = 4096:   27.871 ms (2 allocations: 128.00 MiB)
```
Edit: Benchmark updated for changing `copyto!` instead
<details>
<summary>versioninfo</summary>
```julia
Julia Version 1.8.5
Commit 17cfb8e65e (2023-01-08 06:45 UTC)
Platform Info:
OS: Windows (x86_64-w64-mingw32)
CPU: 8 × 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz
WORD_SIZE: 64
LIBM: …
```
> Faster conversion to dense matrix

- src/solvers/cholmod.jl
This adds explicit typevars to the adjoint cholmod solves as we have them for plain cholmod solves. This )(hopefully) prevents method ambiguities in https://github.com/JuliaLang/julia/pull/46874.
> Obviate future ambiguities in adjoint cholmod solves

- src/SparseArrays.jl
- src/linalg.jl
- test/linalg.jl
This cleans up the `kron` code quite a bit. It follows roughly the concatenation approach, with the exception that it returns a sparse result even when some factors are dense matrices (or wrapped versions thereof).
This fixes #316, which observed a missing case. We may still be missing deeply nested cases, but we don't seem to have a type mechanism to determine upfront whether an array is ultimately sparse.
> Return sparse result in `kron` with one sparse factor

- Project.toml
As noted in https://github.com/JuliaLang/julia/pull/48438 the version field is unset and should match julia's
> Set version to 1.10.0

- test/higherorderfns.jl
Right now we're thinking about changing the `MethodError` message. Unfortunately, this breaks a lot of tests, including this one. Discussion at https://github.com/JuliaLang/julia/pull/47369.
~~If the change below does happen, merge this PR afterwards.
https://github.com/JuliaLang/julia/pull/47369/commits/44367ce8fed017c1aee6a01fb273b12653e7f5c9~~
> Fix "no method matching" test

- .github/workflows/ci.yml
As discussed in https://github.com/JuliaSparse/SparseArrays.jl/pull/340#issuecomment-1419725472
> CI needs to only run on julia master

- src/sparsematrix.jl
- src/sparsevector.jl
I noticed that `float(S)` and `complex(S)` always copy the data, including the index arrays.   I don't think this should be the default, since these methods in `Base` share storage if possible:
```jl
julia> x = rand(ComplexF64, 3); float(x) === x
true
julia> x = rand(ComplexF64, 3); complex(x) === x
true
```
If the caller needs to make a copy of the array, they can do `float.(S)` or `copy(float(S))`.
(It was also inconsistent, because `float` of a sparse *vector* did *not* make a copy of the nonzeros if they were already of a floating-point type, e.g. `ComplexF64`, but *did* copy the indices.)
> float(S) and complex(S) should not copy data unnecessarily

- src/linalg.jl
- src/solvers/cholmod.jl
- test/ambiguous.jl
This is required to merge the recent `kron` changes into Julia Base. Includes now ambiguity testing of `LinearAlgebra`, after loading of `SparseArrays`.
> Resolve `kron` ambiguities

- src/sparsematrix.jl
We have the corresponding ones for `AbtractMatrix`, and need them for `AbstractQ` for https://github.com/JuliaLang/julia/pull/46196.
> Add missing sparse constructors for `AbstractQ`

- src/sparsevector.jl
- test/issues.jl
Silently ignore unrecognized keywords when finding the first index of zero. If stray keywords are passed, they will still cause the inner `sort!` to throw.
Fixes #334
Backport because I introduced this bug in 1.9 in #303.
> Fix bug where non-order keyword arguments are passed from `sort!` to `searchsortedfirst`

- src/SparseArrays.jl
- src/linalg.jl
- src/sparseconvert.jl
- src/sparsevector.jl
This will allow to push https://github.com/JuliaLang/julia/pull/26307 across the finish line. I don't think the intention here was really `AbstractTriangular`, but that the intention was to refer to the LinAlg types, which is exactly what `UpperOrLowerTriangular` is referring to.
> Replace AbstractTriangular by UpperOrLowerTriangular

- src/SparseArrays.jl
- src/solvers/cholmod.jl
- src/solvers/spqr.jl
- src/solvers/umfpack.jl
- src/sparsematrix.jl
- src/sparsevector.jl
This removes some temporary aliases related to `AdjointFactorization` (and prospectively `AdjointQ`).
> Clean up temporary fixes

- Project.toml
- src/abstractsparse.jl
- src/linalg.jl
- src/readonly.jl
- src/solvers/spqr.jl
- src/sparsevector.jl
- test/ambiguous.jl
- test/fixed.jl
- test/sparsevector.jl
- test/spqr.jl
This resolves two ambiguities: comparison of `ReadOnly`s and adjoint vectors times AdjointQ's. This also adds code quality tests via `Aqua.jl`. The new ambiguity test is currently turned off, because it reports the `ReadOnly` ambiguity already existing in the sysimg. After this PR is merged and the stdlib bumped in Julia, the ambiguity test can be turned on. Some other, smaller changes were necessary to help the other code quality checks, like unbound type arguments.
> Test code quality, resolve ambiguities

- src/linalg.jl
- src/sparsevector.jl
I kept the diff minimal. Internally, we could replace all of these aliases by their untyped version, because the type parameters were previously (before #355) used only in 1 or 2 cases "for convenience", i.e., without effect on multiple dispatch, otherwise untyped.
> Bring back typed aliases

- test/spqr.jl
> Fix seed in rank-deficient qr test

- test/spqr.jl
Turns out our latest SuiteSparse7 build worked out fine, and it fixes #369.
> Re-enable the METIS ordering tests

- Project.toml
- src/solvers/LibSuiteSparse.jl
> Use SuiteSparse_jll for LibSuiteSparse.jl

- gen/generator.toml
Use `SuiteSparse_jll.libsuitesparseconfig` for some symbols (see #379)
> Use libsuitesparseconfig for some symbols

- src/linalg.jl
- src/sparsevector.jl
This is type-piracy, but we cannot change that (until JuliaLang/julia#2326), so at least do not make these method intersections unnecessary slow and complicated for everyone who does not care about SparseArrays and does not load it, and unreliable for everyone who does load it.
> improve cat design

- src/solvers/cholmod.jl
These specializations are unnecessary since the `eltype(Type{AbstractArray{T}}) where T` fallback already ensures this behavior; i.e., the interface of the supertype already provides this.
Removing this was motivated by a discussion in the ttfx Slack channel where vtjnash indicated that these types of superfluous interface-extensions could be considered a form of piracy. 
<details>
This addresses the following entry from a `@snoopr` report:
```jl
inserting eltype(::Type{SparseArrays.CHOLMOD.Dense{T}}) where T<:Union{Float64, ComplexF64} @ SparseArrays.CHOLMOD ~/dev/julia-master/share/julia/stdlib/v1.10/SparseArrays/src/solvers/cholmod.jl:983 invalidated:
backedges: 1: superseding eltype(::Type{<:AbstractArray{E}}) where E @ Base abstractarray.jl:239 with MethodInstance for …
```
> remove `eltype` interface-piracy

- src/sparsematrix.jl
- test/issues.jl
This fixes a typo that was causing #390. (Oops, looks like we need more test coverage :) )
Fixes #390
> Fix typo in source code

- docs/src/index.md
- src/sparsematrix.jl
- test/sparsematrix_constructors_indexing.jl
It is quite common when building sparse matrices that you don’t care about the COO vectors after construction. This patch adds `SparseArrays.sparse!(I, J, V)` and `SparseArrays.spzeros!(I, J)` that reuses the memory for the matrix buffers. This upstreams https://github.com/Ferrite-FEM/Ferrite.jl/blob/2fc40dbb2052b2b12e94512fbb6f139c2de47b8a/src/arrayutils.jl#L90
> Add `sparse!(I, J, V)` and `spzeros!(I, J)`.

- src/linalg.jl
- src/sparsevector.jl
> Revert new hvcat design temporarily

- Project.toml
- src/solvers/LibSuiteSparse.jl
- src/solvers/cholmod.jl
- src/solvers/umfpack.jl
Remove remnants from SuiteSparse 5 such as SuiteSparse_long
Fix #349
> Introduce compat bounds for SuiteSparse

- src/sparsevector.jl
Missed in https://github.com/JuliaSparse/SparseArrays.jl/pull/407, but causing doctest build to fail when we try to use this.
> fully qualify promote_eltypeof call

- test/linalg.jl
This is an intermediate change to make https://github.com/JuliaLang/julia/pull/50058 pass CI. So we need to first merge this here, then bump the stdlib, then merge https://github.com/JuliaLang/julia/pull/50058 (and backport to v1.10), then this test relaxation can be reverted (but doesn't have to), then #396 should be merged, and again bump the stdlib including backport to v1.10... roughly.
> Intermediate test relaxation

- src/sparsematrix.jl
I got bitten by this yesterday, would be worth adding a warning here
> added warning for iterating while mutating a sparse matrix

- docs/src/index.md
- docs/src/solvers.md
I fixed a couple of broken links I found while browsing the docs. In doing so I also noticed that all of the internal `@ref` links in `solvers.md` are broken. Is it possible that it's because of a bad Documenter configuration or something? I thought Documenter would be able to pick up references to symbols in the same package.
> Fix some broken links

- src/sparsevector.jl
- test/ambiguous.jl
> cat performance tweaks

- test/ambiguous.jl
Ref https://github.com/JuliaLang/julia/issues/50055
> Test suite: activate a temp project if we need to install Aqua.jl during the test suite

- src/sparsematrix.jl
- test/sparsematrix_constructors_indexing.jl
Fix https://github.com/JuliaSparse/SparseArrays.jl/issues/399
On main:
```julia
julia> S = sprand(Int8, 20, 20, 0.3);
julia> [S]
1-element Vector{SparseMatrixCSC{Int8, Int64}}:
sparse([2, 3, 4, 8, 9, 13, 14, 16, 18, 2  …  8, 13, 16, 17, 19, 4, 6, 10, 18, 19], [1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 6, 6, 6, 6, 6, 7, 7, 7, 7, 8, 8, 8, 8, 8, 8, 8, 8, 9, 9, 10, 10, 10, 10, 11, 11, 11, 11, 11, 12, 12, 12, 12, 12, 12, 12, 13, 13, 13, 13, 13, 13, 13, 13, 13, 14, 14, 14, 15, 15, 15, 15, 15, 15, 16, 16, 16, 16, 16, 16, 17, 17, 17, 17, 17, 18, 18, 18, 18, 18, 19, 19, 19, 19, 19, 20, 20, 20, 20, 20], Int8[108, 6, -86, 17, 48, 51, 23, 88, 82, -24  …  -27, -3, 24, -56, 109, 73, 70, 101, -100, 46], 20, 20)
```
This PR
```julia …
```
> Respect `IOContext` while displaying a `SparseMatrixCSC`

- docs/src/index.md
Fix https://github.com/JuliaLang/julia/pull/51050
> Fix docs conflict when building as part of full Julia docs

- src/sparsevector.jl
The generic `cat` does more shape analysis, that typed_cat does not always do (before either may then dispatch to _cat_t), so we can make this faster by calling it instead.
Secondly, we can make `issparse` non-recursive once it hits a base case where all trailing elements are the same. This makes it much better at handling large splat, since we do not need to check each recursively smaller type down to the base case using generic code, and just generate one const method specialized on the full length instead.
Fix JuliaLang/julia#51011
> faster cat performance

- src/sparsematrix.jl
- test/sparsematrix_constructors_indexing.jl
This PR includes two fixes:
It is a simple obvious fix to the problem when one tries to do something like the following
```julia
using SparseArrays, StaticArrays
const Vec2 = SVector{2, Float64}
A = rand(Vec2, 2, 2) |> sparse
fill!(view(A, :, :), zero(Vec2))
```
Without the fix, it throws
```
ERROR: MethodError: Cannot `convert` an object of type Int64 to an object of type SVector{2, Float64}
Closest candidates are:
convert(::Type{T}, ::Factorization) where T<:AbstractArray
@ LinearAlgebra /usr/share/julia/stdlib/v1.9/LinearAlgebra/src/factorization.jl:59
convert(::Type{SVector{N, T}}, ::CartesianIndex{N}) where {N, T}
@ StaticArrays ~/.julia/packages/StaticArrays/jA1zK/src/SVector.jl:13
convert(::Type{SA}, ::Tuple) where SA<:StaticArray
@ StaticArrays …
```
> Correctly set zeros with `fill!(::SubArray)` and fix its return value

- src/linalg.jl
The changed function is a little bit faster than the current one.
```julia
N1 = 1024*10
N2 = 1024*20
T = Float64
x = Array(sprand(T, N1, 0.1))
y = Array(sprand(T, N2, 0.1))
A = sprand(T, N1, N2, 1/N1)
@benchmark dot($x, $A, $y)
BenchmarkTools.Trial: 10000 samples with 1 evaluation.
Range (min … max):  45.800 μs … 287.700 μs  ┊ GC (min … max): 0.00% … 0.00%
Time  (median):     57.800 μs               ┊ GC (median):    0.00%
Time  (mean ± σ):   58.845 μs ±  10.107 μs  ┊ GC (mean ± σ):  0.00% ± 0.00%
▁█                                               
▁▁▂▃▄▅▅▃▃▄▃▃▄██▆▄▃▂▃▂▂▂▂▁▁▂▁▂▂▂▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁ ▂
45.8 μs         Histogram: frequency by time         96.6 μs <
Memory estimate: 0 bytes, allocs estimate: 0.
@benchmark mydot($x, $A, $y)
BenchmarkTools.Trial: 10000 samples with 1 …
```
> Improved the dot product between two vectors and a sparse matrix

- src/linalg.jl
- src/solvers/cholmod.jl
- src/sparsematrix.jl
- src/sparsevector.jl
There should be little performance impact:
```julia
julia> x = cumsum(rand(1000));
julia> @btime searchsortedfirst($x, 250, 400, 600, Base.Forward)
14.612 ns (0 allocations: 0 bytes)
510
julia> @btime searchsortedfirst(view($x, 400:600), 250)
14.612 ns (0 allocations: 0 bytes)
111
```
See JuliaLang/julia#51177 and JuliaLang/julia#51176 for motivation
> Switch from internal 5-arg `searchsorted*` methods to views

- src/solvers/umfpack.jl
Fixes https://github.com/JuliaSparse/SparseArrays.jl/issues/448
Add a note to the documentation for `lu`, explaining that Julia modifies the UMFPACK defaults to disable iterative refinement.
Add an example to illustrate usage of the UMFPACK control vector to reenable iterative refinement
> Add example for UMFPACK control vector

- docs/src/index.md
The current documentation claims that `findall(!iszero, my_sparse_matrixcsc)` would be "including stored entries equal to zero".
This seems counter-intuitive to me. It also seems to be wrong (unless I'm missing something):
```julia
julia> M = sparse([1, 2], [1,1], [0, 1], 2, 2)
2×2 SparseMatrixCSC{Int64, Int64} with 2 stored entries:
0  ⋅
1  ⋅
julia> findnz(M)
([1, 2], [1, 1], [0, 1])
julia> findall(!iszero, M)
1-element Vector{CartesianIndex{2}}:
CartesianIndex(2, 1)
```
I propose to correct the documentation.
> Fix documentation of `findall` behaviour

- docs/Project.toml
- docs/make.jl
- docs/src/solvers.md
- src/linalg.jl
- src/solvers/cholmod.jl
- src/sparsematrix.jl
- src/sparsevector.jl
- test/ambiguous.jl
- test/linalg.jl
- test/sparsematrix_constructors_indexing.jl
> Backports for Julia v1.10

- Project.toml
Should be backported to 1.10 as well.
> Bump SuiteSparse to 7.2.1

- src/sparsematrix.jl
This improves performance and reduces allocation:
```julia
julia> S = sprand(1000, 1000, 0.04);
julia> @btime $S + $(Array(S));
2.107 ms (4 allocations: 15.26 MiB) # main
1.539 ms (2 allocations: 7.63 MiB) # PR
```
> Don't materialize when adding/subtracting an `Array`

- docs/src/index.md
[Finch](https://github.com/willow-ahrens/Finch.jl) is a library for multidimensional sparse array processing that supports a wide variety of formats and operators. It's one of the few Julia libraries to support sparse tensors, it's highly flexible, and it's design could only exist in Julia. Would you please consider adding it to the list?
> Add Finch to list of External Julia Sparse Array Libraries

- src/sparsevector.jl
Fixes https://github.com/JuliaLang/julia/issues/51826
(looks like hvcat was already correct, but somehow these got copied wrong from where ever they came from)
> fix h/vcat invoke dispatch arguments

- src/linalg.jl
- src/sparsevector.jl
Since `tA` is usually known from the types, this helps eliminate branches. Strangely, Cthulhu suggests that `LinearAlgebra.wrap` call within `spdensemul!` is still inferred as a `Union`, but this doesn't matter much as there's a function barrier.
> Aggressive constprop in sparse * dense

- src/higherorderfns.jl
- src/sparsematrix.jl
Fix #441
```julia
julia> S = sparse([1,2,2,2,3], [1,1,2,2,4], [5, -19, 73, 12, -7])
3×4 SparseMatrixCSC{Int64, Int64} with 4 stored entries:
5   ⋅  ⋅   ⋅
-19  85  ⋅   ⋅
⋅   ⋅  ⋅  -7
julia> Sv = view(S, :, 1:3)
3×3 view(::SparseMatrixCSC{Int64, Int64}, :, 1:3) with eltype Int64:
5   0  0
-19  85  0
0   0  0
julia> Sv + Sv
3×3 SparseMatrixCSC{Int64, Int64} with 3 stored entries:
10    ⋅  ⋅
-38  170  ⋅
⋅    ⋅  ⋅
```
> Algebraic operators for SparseMatrixCSCView

- test/higherorderfns.jl
Several of these are failing being slightly over the threshold on some CI runs. Relax all the thresholds, since the intent is to make sure allocations are completely dynamic, not to prohibit them entirely.
C.f. https://buildkite.com/julialang/julia-master/builds/29821#018bab25-9f95-4abd-aabf-6eaa8c05859e for example
> test: relax allocated tests

- Project.toml
- test/ambiguous.jl
This change makes updating Aqua and getting all new functionality as easy as bumping the compat version (for breaking releases).
With the current setup, you don't get any new tests.
Furthermore, we added functionality in Aqua itself to mark certain tests as `broken`.
Lastly, `detect_unbound_args_recursively` and `Piracies.hunt` are purely internal and subject to change in a non-breaking release in the near future.
cc @DilumAluthge
> Simplify calling Aqua

- .github/workflows/CompatHelper.yml
- .github/workflows/ci.yml
- Project.toml
- test/ambiguous.jl
- test/runtests.jl
- test/testgroups
CI on Julia 1.10 backport branch errors due to this.
> Backport Aqua fixes to 1.10.

- Project.toml
- src/solvers/cholmod.jl
- test/cholmod.jl
Incomplete, posting now for codecov purposes. There are some outstanding issues on how to do promotion and conversion, since the CHOLMOD built-in capabilities are limited.
> Add Support for Single Precision

- src/sparsematrix.jl
- test/issues.jl
Handles the `SparseArrays` part of https://github.com/JuliaLang/julia/issues/52725.
The docstring was already there, it was just attached to the wrong function.
In which file should I put the test?
```julia
@test Docs.undocumented_names(SparseArrays) == []
```
cc @stevengj
> Move `fkeep!` docstring to the right function

- src/solvers/cholmod.jl
@rayegun I am not sure if this is right. I couldn't find `cholmod_common_l` anywhere.
> Fix error message in getcommon() in cholmod

- src/sparsematrix.jl
- test/sparsematrix_ops.jl
1. Parameterised `_findr()` on the element type of the sparse array. Otherwise, every single `op()` comparison allocates, every time `_findr()` is called (not sure if there is another way to optimise those allocations away).
2. Added a keyword argument `dims` to the existing functions, with default values to preserve current behaviours when `dims` is not provided.
3. Changed the type of `_findr()` a bit. It's not used anywhere else, and the change simplifies the previous changes.
(Example: https://pastebin.com/raw/47xxMkHa shows different allocation and timing behaviour at different stages of the 2 included commits. The direct `_findr()` needs to be adjusted to account for the type change)
Fixes #510.
> Speedup for `findmin()/findmax()` on sparse arrays (#510)

- .github/workflows/ci.yml
GitHub Actions now offers free Apple Silicon macOS runners for public repositories:
> Today, GitHub is excited to announce the launch of a new M1 macOS runner! This runner is available for all plans, free in public repositories, and eligible to consume included free plan minutes in private repositories. The new runner executes Actions workflows with a 3 vCPU, 7 GB RAM, and 14 GB of storage VM, which provides the latest Mac hardware Actions has to offer. The new runner operates exclusively on macOS 14 and to use it, simply update the `runs-on` key in your YAML workflow file to `macos-14`.
https://github.blog/changelog/2024-01-30-github-actions-introducing-the-new-m1-macos-runner-available-to-open-source/
https://discourse.julialang.org/t/github-actions-now-offers-free-apple-silicon-macos-ru …
> CI: Add Apple Silicon (macOS aarch64) to the CI matrix

- src/solvers/spqr.jl
Does this make sense?
Closes #515
```julia
julia> using SparseArrays, ForwardDiff, LinearAlgebra
julia> A = ForwardDiff.Dual.(sprand(10, 10, 0.1));
julia> qr(A)
ERROR: MethodError: no method matching Float64(::ForwardDiff.Dual{Nothing, Float64, 0})
The type `Float64` exists, but no method is defined for this combination of argument types when trying to construct it.
```
> cast to Float64 directly instead of using float

- test/runtests.jl
- test/util/gha.jl
Ref #531
Alternative to #529 (closes #529)
1. Do run `threads` tests on non-Windows
2. Do run `threads` tests on Windows on Buildkite CI
3. Do NOT run `threads` tests on Windows on GitHub Actions CI
> CI: don't run `threads` tests in Windows GHA CI (attempt 2)

- src/sparsematrix.jl
- src/sparsevector.jl
- test/sparsematrix_constructors_indexing.jl
- test/sparsevector.jl
With this, the following works:
```julia
julia> similar(SparseMatrixCSC{Float64,Int}, 2,2)
2×2 SparseMatrixCSC{Float64, Int64} with 0 stored entries:
⋅    ⋅ 
⋅    ⋅ 
```
Previously, this used to call the `SparseMatrixCSC` constructor with a `Tuple` of `Int`s, which was not defined. Similar constructors are added for `SparseVector`.
This should probably be backported to v1.11 as well as v1.10. I added the backport 1.10 label, but there doesn't seem to be one for v1.11.
> SparseMatrixCSC constructor with a Tuple of Integers

- src/SparseArrays.jl
- src/sparsematrix.jl
- test/sparsematrix_ops.jl
```julia
julia> S = sprand(100, 100, 0.01);
julia> M = zeros(size(S));
julia> @btime copytrito!($M, $S, 'U');
20.779 μs (0 allocations: 0 bytes) # main
2.050 μs (0 allocations: 0 bytes) # this PR
```
> Extend `copytrito!` for a sparse source

- .gitignore
Julia v1.11 supports Manifest files with the version in the filename, and we may ignore these files as well.
> Add versioned Manifest files to .gitignore

- Project.toml
- src/SparseArrays.jl
- src/linalg.jl
- src/sparsevector.jl
This is a companion PR to https://github.com/JuliaLang/julia/pull/52439. It pushes creation of `MulAddMul`  objects down the call path, so avoids it in all cases except for in-place sparse multiplication.
> Adjust matvec and matmatmul! to new internal LinAlg interface

- src/sparsematrix.jl
- src/sparsevector.jl
- test/sparsematrix_constructors_indexing.jl
- test/sparsevector.jl
Calling `repeat` for sparse matrices or vectors currently calls the `Base` function, which ends up building the result rather inefficiently with indexing brackets.
This would add sparse versions that use the info that inputs are in CSC format to provide more efficient implementations. To keep it simple it is limited to the straightforward cases of outer repetition along the first two dimensions. Row-wise repetition is intentionally kept close to the implementation for `vcat`, also using its helper function `stuffcol!` (with slight modifications). Column-wise repetition is kept simple by deferring to `Base.repeat` on the `colptr`, `rowval`, and `nzval` components of the CSC format.
> Sparse versions of repeat for matrices and vectors

- test/spqr.jl
- test/umfpack.jl
with [#54504](https://github.com/JuliaLang/julia/pull/54504) field access exception is raised as `FieldError` exception now.
> tests to use fallback exception to handle `FieldError` exception

- test/cholmod.jl
- test/linalg_solvers.jl
- test/spqr.jl
- test/umfpack.jl
The GPL module `SparseArrays.CHOLMOD` has already been used before the `if Base.USE_GPL_LIBS` statement.
This results in the error
```
ERROR: LoadError: UndefVarError: `CHOLMOD` not defined in `SparseArrays`
Stacktrace:
```
> test: Don't use GPL module when Base.USE_GPL_LIBS=false

- src/solvers/cholmod.jl
- test/cholmod.jl
I have implemented an in-place `ldiv!` for Cholesky factorizations of sparse matrices. 
Closes #319 
Closes #275
Closes #123
Xref https://discourse.julialang.org/t/is-there-no-ldiv-for-choleski-factorization-of-a-sparse-matrix/114806
The method works locally but is not as elegant as the UMFPack/LU version or the other code in the CHOLMOD wrapper:
- UMFPack accepts arrays/pointers directly whereas CHOLMOD uses `cholmod_dense` structs.
- The `Dense` wrappers in the Julia CHOLMOD module allocate new arrays.
Thus, the code looks a bit different from the remaining code in the file.
The current method still allocates some memory on my system since we do not provide the workspace vectors `Handle_Y` and `Handle_E`. We could store them in the `CHOLMOD.Factor` struct. I tried that, but they were …
> implement in-place `ldiv!` for Cholesky factorization

- src/solvers/spqr.jl
SPQR uses just the double precision epsilon even for Float32.
https://github.com/DrTimothyAldenDavis/SuiteSparse/blob/131471310ef0600b231b8fa7c10a55c3f70afbd9/SPQR/Source/spqr_tol.cpp#L29C6-L30C57
> Change default QR tolerance to match SPQR

- src/linalg.jl
- test/linalg.jl
After this,
```julia
julia> using SparseArrays, LinearAlgebra
julia> D = Diagonal(1:4)
4×4 Diagonal{Int64, UnitRange{Int64}}:
1  ⋅  ⋅  ⋅
⋅  2  ⋅  ⋅
⋅  ⋅  3  ⋅
⋅  ⋅  ⋅  4
julia> S = sprand(4, 4, 0.2)
4×4 SparseMatrixCSC{Float64, Int64} with 6 stored entries:
0.8632  0.206049   ⋅        0.921636
⋅       ⋅        0.49266    ⋅ 
⋅       ⋅        0.329707   ⋅ 
⋅       ⋅         ⋅        0.69844
julia> D * S * D
4×4 SparseMatrixCSC{Float64, Int64} with 6 stored entries:
0.8632  0.412098   ⋅        3.68655
⋅       ⋅        2.95596    ⋅ 
⋅       ⋅        2.96736    ⋅ 
⋅       ⋅         ⋅       11.175
```
This operation of pre- and post-multiplication by `Diagonal`s is not uncommon, as it scales the rows and columns of the sandwiched matrix. After this PR, the result is a sparse matrix as well.
The …
> Diagonal-sandwiched triple product for SparseMatrixCSC

- src/linalg.jl
- test/linalg.jl
> added specialized method for 3-argument dot with diagonal matrix

- src/linalg.jl
> Inline sparse-times-dense in-place multiplication

- docs/src/index.md
- docs/src/solvers.md
When building julia with `USE_GPL_LIBS:=0`, the documentation builds fails because the documentation for the solver cannot be found.
Only `docs/src/index.md` is copied when building the documentation, so we can move the solver documentation to `docs/src/solver.md` to avoid this problem.
See: https://github.com/JuliaLang/julia/issues/56344
> doc: move solvers doc to `src\solvers.md`

- src/linalg.jl
- test/linalg.jl
Adds a specialization for the out-of-place multiplication of Diagonal * sparse-vector, otherwise the current version was O(n) instead of O(nnz)
> added diagonal-sparse multiplication

- src/sparsevector.jl
Backport of  https://github.com/JuliaSparse/SparseArrays.jl/pull/579
> Backport 14333eae647464121150ae77d9f2dbe673aa244b to 1.10

- src/abstractsparse.jl
- test/allowscalar.jl
Goes along with https://github.com/JuliaLang/julia/pull/56509
> Make `allowscalar` a macro with auto-world-age-increment

- src/sparsematrix.jl
- test/sparsematrix_ops.jl
Currently, only `istriu(S)` and `istril(S)` are specialized for sparse matrices, and this PR generalizes these to accept the band index `k`. This improves performance:
```julia
julia> S = sparse(1:4000, 1:4000, 1:4000);
julia> @btime istriu($S, -1);
20.941 ms (0 allocations: 0 bytes) # main
5.660 μs (0 allocations: 0 bytes) # this PR
```
> Generalize `istriu`/`istril` to accept a band index

- src/sparsematrix.jl
- src/sparsevector.jl
Some functions were documented as applying only to matrices but they actually work for vectors too.
> Mention vectors in more docstrings

- src/sparsevector.jl
It looks like in base that error was only enabled on number inputs, lets see if this fixes it?
cc @gbaraldi @KristofferC
> More adhereance to 1.10 error types (hopefully)

- src/solvers/cholmod.jl
- test/cholmod.jl
> Solve with `AdjointFactorization` of Cholmod and `Adjoint` rhs

- src/SparseArrays.jl
These would otherwise give a warning after JuliaLang/julia#57311, but are a good change even independently.
> Explicitly declare type constructor imports

- src/solvers/cholmod.jl
- src/solvers/spqr.jl
- test/spqr.jl
I fixed the same bug as #585, without realizing that it had already been done. It wasn't a complete waste of time, because the PR #586 left some cleanup to do: the lines
```julia
LinearAlgebra.qr(A::SparseMatrixCSC{<:Union{Float16,Float32}}; tol=_default_tol(A)) =
qr(convert(SparseMatrixCSC{Float64}, A); tol=tol)
LinearAlgebra.qr(A::SparseMatrixCSC{<:Union{ComplexF16,ComplexF32}}; tol=_default_tol(A)) =
qr(convert(SparseMatrixCSC{ComplexF64}, A); tol=tol)
```
would have prevented it from working if they actually worked! Luckily they don't, as the correct method is more specific and gets called, but it's still worth fixing. I also changed them to convert `Float16` to `Float32` instead of `Float64`, and the analogous change for complex numbers.
I also fixed the error messages one gets. They …
> cleanup support for Float32 and ComplexF32

- src/solvers/cholmod.jl
These were being extended in the module, but weren't explicitly imported from `Base`.
> Explicitly import `Matrix` and `Vector` in CHOLMOD

- src/higherorderfns.jl
- src/linalg.jl
- src/solvers/cholmod.jl
- src/solvers/spqr.jl
- src/solvers/umfpack.jl
- src/sparsematrix.jl
- src/sparsevector.jl
This generally makes it easier to read code, as one doesn't need to look up variable definitions from elsewhere.
> Use `axes` instead of `1:size`

- src/sparsematrix.jl
- src/sparsevector.jl
The purpose of this PR is to not call `==` directly, and use `_iszero` instead. This is to help integration with [IntervalArithmetic.jl](https://github.com/JuliaIntervals/IntervalArithmetic.jl) since `==` for our `Interval` type does not always return a Boolean.
Closes https://github.com/JuliaSparse/SparseArrays.jl/issues/609.
I did not change two checks using `===` since this would break the behaviour for `-0.0`. If I understood correctly, it should not be an issue with `Interval`, since it will return `false` consistently (it may be sub-optimal, but not wrong)
cc @dpsanders, @Kolaru
cc also @kalmarek, since you raised https://github.com/JuliaIntervals/IntervalArithmetic.jl/issues/628 you may have more experience mixing SparseArrays and IntervalArithmetic
I do not know how to the …
> Replace `v == zero(v)` with  `_iszero`

- src/linalg.jl
- test/linalg.jl
This improves performance:
```julia
julia> using LinearAlgebra, SparseArrays
julia> D = Diagonal(rand(3000));
julia> S = sprand(size(D,1), 0.01);
julia> @btime ldiv!($D, $S);
30.053 μs (0 allocations: 0 bytes) # master
1.585 μs (0 allocations: 0 bytes) # PR
```
> `ldiv!` for `Diagonal` and a sparse vector

- src/linalg.jl
These methods do not require the `eltype`s to match exactly, and should work as long as the values may be stored in the destination.
> Relax `eltype` in `Diagonal` `ldiv!`/`rdiv!`

- src/solvers/cholmod.jl
I find it worth pointing out explicitly in the docs that LDLt, which mathematically looks like a drop-in replacement for Cholesky that does away with the positive definiteness requirement, comes with the following caveats:
* It fails for a lot of matrices (for example, `ldlt(Symmetric(sprandn(1000, 1000, p)))` basically never succeeds for any relevant sparsity `p`) due to the requirement that all leading principal minors be well-conditioned
* In CHOLMOD, `ldlt` is significantly slower than `cholesky` as it does not have a supernodal implementation
So I made some docstring edits to clarify the relationship and tradeoffs between `cholesky` and `ldlt`.
Citation for these claims: pages 106-107 in the CHOLMOD user guide at https://github.com/DrTimothyAldenDavis/SuiteSparse/blob/v7.10.3/CHOLMOD/ …
> Clarify pros, cons and limitations of Cholesky and LDLt

- src/linalg.jl
- src/solvers/cholmod.jl
- src/sparsematrix.jl
- src/sparsevector.jl
- test/linalg.jl
> Backports for v1.12

- src/solvers/cholmod.jl
On top of https://github.com/JuliaSparse/SparseArrays.jl/pull/625
> Lazily init cholmod

- src/linalg.jl
Changed error message when trying to compute condition number of sparse matrix in 2-norm, suggesting 1 or Inf norm.
Newbies like me or https://discourse.julialang.org/t/condition-number-of-sparse-matrix/77131/5 got diverted into trying densifying the array, which is very limited in many applications...
> Make cond(::SparseMatrix, 1 / Inf) discoverable from 2-norm error

- src/linalg.jl
- test/linalg.jl
This generalizes all-sparse 3-arg `dot` to non-(real or complex) eltypes, such as `Quaternion`s.
> Extend 3-arg `dot` to generic `HermOrSym` sparse matrices

- src/linalg.jl
- test/linalg.jl
This was missing from the specializations and thus still slow.
This is a port from the same PR on FW.jl: https://github.com/ZIB-IOL/FrankWolfe.jl/pull/607
> fast quadratic form for dense matrix, sparse vectors

- src/readonly.jl
* Define only single-argument methods for `size` and `axes`.
* On Nightly Julia, this change prevents two sysimage invalidations, triggered by defining two-argument `axes`.
* Do not add the `eltype` method.
* New types are not supposed to define `eltype` on instances.
* New subtypes of `AbstractArray` are not supposed to add methods to `eltype`.
> `ReadOnly` fixes: prevent adding some methods of `size`, `axes`, `eltype`

- src/solvers/cholmod.jl
One of the methods in question can be simply deleted because `IndexCartesian` is the default.
The other one is changed to be defined on the type instead of on the instance, as intended.
Preventing defining `IndexStyle` methods on instances (as opposed to types) prevents a single invalidation.
> cholmod: correct the `IndexStyle` method additions

- src/readonly.jl
Do not add single-argument methods to:
* `eachindex`
* `firstindex`
* `lastindex`
The above have fallbacks that work as intended as long as the two two-argument methods of `eachindex` are defined.
So add the two-argument methods of `eachindex` instead of adding single-argument methods of the three functions.
On nightly Julia, together with PR #652, this PR decreases the amount of sysimage invalidations that happen when loading SparseArrays from $26$ to $17$.
Without PR #652, this PR happens to increase the amount of invalidations, to $28$.
> `ReadOnly`: do not add single-argument methods to `eachindex`, etc
