JuliaSparse/SparseArrays.jl

.github/workflows/ci.yml

Update actions to v2
Not sure how to get the gh-pages branch created.

Try to get docs deployed

---

src/sparsematrix.jl

This is a duplicate of https://github.com/JuliaLang/julia/pull/42549, which was closed when SparseArrays was split off.
Original message below:
---------------------------------------------------------------
This PR changes a few more instances of literal 0's to the more appropriate zero or iszero method for when the eltype of the SparseArray cannot be compared directly with 0.
See also JuliaLang/julia#42536 and #46 for some recent issues related to this.

Change some instances of literal `0` to `zero`/`iszero`

---

src/sparsematrix.jl
test/sparse.jl

Use index-generic bounds checking

---

src/solvers/umfpack.jl
test/solvers/umfpack.jl

Is this what i was supposed to do? with some luck i managed to "transfer" the commits...

Umfpack Thread safety fix

---

src/sparsematrix.jl

use summary(array) for invalid-buffer error message

---

Project.toml
test/runtests.jl
test/sparsevector.jl

Fix accidental removal of SparseArrays.jl tests

---

test/solvers/umfpack.jl

Temporarily resolves: https://github.com/JuliaLang/julia/issues/45736

Temporarily remove tests for 16-bit eltypes

---

docs/make.jl
docs/src/solvers.md

@Wimmerer Can you check to see if this is the right way to do this?

Add solver docs to SparseArrays docs

---

src/solvers/cholmod.jl
src/solvers/spqr.jl
src/solvers/umfpack.jl

Pulling in @Wimmerer 's https://github.com/JuliaSparse/SuiteSparse.jl/pull/69/files

Remove extra citations that don't have corresponding footnotes

---

docs/src/index.md

Remove Transpose and Adjoint docs temporarily

---

test/umfpack.jl

Should help https://github.com/JuliaSparse/SparseArrays.jl/issues/147
Also only disables the Float16 tests on windows.

Disable Float16 approximate tests on Windows

---

src/solvers/umfpack.jl

@ViralBShah that's all of them as far as i can see but should i also set the non pointer refs to zero?

umfpack: initialize pointers to null

---

test/umfpack.jl

maybe this will help but it will make the tests take longer

test umfpack sanity

---

test/ambiguous.jl

i should have not moved the test to the main test file. fixes the failure in https://github.com/JuliaLang/julia/pull/46026

import test in ambigous.jl

---

src/solvers/spqr.jl
test/spqr.jl

add tolerance to rank

---

src/solvers/umfpack.jl
test/umfpack.jl

should make everyone's life one line easier

umfpack: overload duplicate for transposed LUs

---

src/solvers/umfpack.jl
test/umfpack.jl

de-serialize didn't de-serialize the lock. maybe there should be some test to make sure de-serialize consumes everything?

don't skip lock in deserialize umfpacklu

---

src/sparsematrix.jl
test/issues.jl

also make it non-allocating.
closes #210

fix show for adjoint/transpose of CSC matrices.

---

src/SparseArrays.jl
src/abstractsparse.jl
src/linalg.jl
src/sparsematrix.jl
src/sparsevector.jl
test/issues.jl
test/sparsematrix_ops.jl

closes #15
replaces a bunch of `!iszero` with `_isnotzero` in order to handle `Missing`.

use _isnotzero(v)

---

test/umfpack.jl

should fix the failure in 3b53e587a5655db4822dacbe32430dae24c7c8ee

fix deserialize tests

---

src/solvers/spqr.jl
test/spqr.jl

add docs to rank, block qr(CSC, PiovotStrategy)

---

src/higherorderfns.jl
test/higherorderfns.jl

Closes https://github.com/JuliaSparse/SparseArrays.jl/issues/221.

map: Avoid calling f on zero unless necessary

---

src/linalg.jl
test/linalg.jl

Closes https://github.com/JuliaSparse/SparseArrays.jl/issues/235.

Make kron with [Bi,Tri]diagonal matrices more efficient

---

src/solvers/umfpack.jl

Failed a doctest I didn't catch on this repo somehow

Remove accidental duplicate method, fix doctest (locally)

---

src/linalg.jl

Clean up mul/div code of sparse and diagonal

---

src/SparseArrays.jl
src/solvers/cholmod.jl
src/solvers/umfpack.jl

This adds necessary changes related to https://github.com/JuliaLang/julia/pull/46874. This could be merged even before that linalg PR, because it doesn't check `VERSION`.

Adjust to `[Adjoint/Transpose]Factorization`

---

src/linalg.jl

Recently introduced by me in #331.

Avoid piracy in `kron`

---

src/SparseArrays.jl
src/solvers/cholmod.jl
src/solvers/umfpack.jl
test/umfpack.jl

The fallback will say that transpose of real factorizations should return an adjoint factorization, so we need to override this.

Make sure transpose(UmfpackLU) is Transpose[Factorization]

---

src/solvers/cholmod.jl

Fixes https://github.com/JuliaSparse/SparseArrays.jl/issues/332
~I have not been able to test locally.~

Handle SuiteSparse >= 7

---

src/abstractsparse.jl
src/sparsematrix.jl
src/sparsevector.jl
test/cholmod.jl

Corrects some typos that I've found in the repository.

Correct some typos

---

test/sparsevector.jl

This should resolve the failure seen in https://buildkite.com/julialang/julia-master/builds/28643#018b1f0a-00d9-4628-ad71-aa816bb8881a

Interpolate SparseVector in display test

---

test/sparsematrix_ops.jl

For https://github.com/JuliaLang/julia/pull/44702

test: somewhat more permissive test_throws message

---

.github/workflows/CompatHelper.yml
Project.toml

Not having a compat for Aqua caused a failure in julia CI when Aqua released breaking change v0.8.0

Add Aqua compat. Create CompatHelper.yml

---

src/linalg.jl
test/linalg.jl

Closes https://github.com/JuliaLang/julia/issues/52230.

Extend sparse kron to adjortrans of dense matrices

---

Project.toml
gen/Project.toml

The CI is expected to fail here.

Update to SuiteSparse 7.5.1

---

src/sparsevector.jl

Provide a message when throwing DimensionMismatch

---

.github/workflows/ci.yml

Reverts JuliaSparse/SparseArrays.jl#525

Revert "Don't fail CI if codecov upload fails."

---

.github/workflows/ci.yml
src/solvers/cholmod.jl

Manual commit for PR #550 to backport to 1.10
